name: instagram_clone
description: A Flutter Instagram profile clone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/videos/video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4
    - assets/videos/video4.mp4
    - assets/videos/video5.mp4
    - assets/videos/video6.mp4